"""Build a curated framework catalog seed from a public LibreTexts book.

Publishing a generated item to ADAPT requires a curated framework topic whose
canonical URL matches the draft's source page. Without one the publisher
refuses (see ``app/publishing.py``). That gate is a *seeding* limit, not a
product limit: ``app/catalog.py`` globs ``app/catalogs/*.json``, so any book
becomes publishable once a seed for it exists. Writing those by hand does not
scale past a couple of books, which is what this script is for.

Chapter and topic identity
--------------------------
``stable_id`` is a UUID5 over the page's canonical URL, inside a per-book
namespace that is itself a UUID5 of the book URL. That makes identity a pure
function of the URL: regenerating a seed for an unchanged book reproduces the
same IDs, so alignments already published into ADAPT keep resolving.

The flip side is that a seed generated by a *different* scheme has different
IDs for the same pages. Overwriting one of those would silently orphan every
question already published against it, so ``--force`` is required to replace a
seed whose IDs this script does not reproduce.

Installing a seed
-----------------
A catalog has to land in **both** repositories, byte for byte:

* Assessment AI -- ``app/catalogs/``
* ADAPT -- ``resources/frameworks/``

``scripts/verify_framework_catalogs.py`` compares the two by SHA-256 and fails
if they diverge. Both are baked into their images, so both need a rebuild
before a new book can actually be published against.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Callable, Sequence
from uuid import NAMESPACE_URL, UUID, uuid5

SCHEMA_VERSION = 1
USER_AGENT = "libretexts-dev catalog seed generator"
REQUEST_TIMEOUT = 45
POLITE_DELAY = 0.4

# Subpage listing markup, used when the Deki API is not open on a subdomain.
_LISTING_ANCHOR_RE = re.compile(r"(<a\b[^>]*>)(.*?)</a>", re.S | re.I)
_HREF_RE = re.compile(r'href="([^"]+)"', re.I)
_TITLE_SPAN_RE = re.compile(
    r"<span[^>]*\bmt-sortable-listing-title\b[^>]*>(.*?)</span>", re.S | re.I
)
_TITLE_ATTR_RE = re.compile(r'title="([^"]*)"', re.I)

# Front/Back Matter carry no assessable content and are excluded from the
# curated seeds that already ship, so the generated ones match that shape.
SKIPPED_TITLES = frozenset({"front matter", "back matter", "index", "glossary"})

HttpGet = Callable[[str], str]


class SeedGeneratorError(RuntimeError):
    """Raised for any condition that should stop seed generation."""


@dataclass(frozen=True)
class Page:
    """One node of a book's table of contents."""

    title: str
    canonical_url: str
    has_children: bool


@dataclass
class BookOutline:
    """A book plus its chapters, each chapter with its own topic pages."""

    source_url: str
    title: str
    chapters: list[tuple[Page, list[Page]]] = field(default_factory=list)


def normalize_source_url(value: str) -> str:
    """Canonicalize a URL for identity comparisons.

    Mirrors ``app.catalog.normalize_source_url``. It is duplicated rather than
    imported so this script stays runnable without importing the application,
    and a test asserts the two implementations agree.
    """

    parsed = urllib.parse.urlsplit(value.strip())
    path = urllib.parse.quote(urllib.parse.unquote(parsed.path), safe="/").rstrip("/")
    return urllib.parse.urlunsplit(
        (parsed.scheme.lower(), parsed.netloc.lower(), path, "", "")
    )


def namespace_for(source_url: str) -> UUID:
    """The per-book UUID5 namespace that chapter and topic IDs live in."""

    return uuid5(NAMESPACE_URL, normalize_source_url(source_url))


def stable_id_for(namespace: UUID, canonical_url: str) -> str:
    """Identity for one page: a pure function of its *normalized* URL.

    Normalizing first is load-bearing, not tidiness. The Deki API returns
    ``..._(Levitus)/...`` while the curated seeds store ``..._%28Levitus%29/...``
    for the same page. Hashing the raw string would mint a different id
    depending on where the URL came from, which is exactly the drift that
    breaks alignments already published into ADAPT.
    """

    return str(uuid5(namespace, normalize_source_url(canonical_url)))


def _http_get(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT) as response:
            body = response.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as error:
        raise SeedGeneratorError(f"{url}: HTTP {error.code}") from error
    except urllib.error.URLError as error:
        raise SeedGeneratorError(f"{url}: {error.reason}") from error
    time.sleep(POLITE_DELAY)  # only on a real fetch; be a good citizen
    return body


def subpages_api_url(page_url: str) -> str:
    """The Deki subpages endpoint for a page, addressed by its path.

    LibreTexts runs NICE CXone Expert (Deki), which exposes a public read-only
    API. ``=<double-encoded path>`` is Deki's "address this page by path rather
    than numeric id" form, so no page-id lookup is needed.
    """

    parsed = urllib.parse.urlsplit(normalize_source_url(page_url))
    if not parsed.scheme or not parsed.netloc:
        raise SeedGeneratorError(f"not an absolute URL: {page_url}")
    path = parsed.path.lstrip("/")
    if not path:
        raise SeedGeneratorError(f"URL has no page path: {page_url}")
    # Deki wants the path encoded a second time, %2F and all.
    encoded = urllib.parse.quote(path, safe="")
    return (
        f"{parsed.scheme}://{parsed.netloc}"
        f"/@api/deki/pages/={encoded}/subpages?dream.out.format=json"
    )


def _text_of(value: Any) -> str:
    """Deki renders some fields as a bare string and others as ``{'#text': ...}``."""

    if isinstance(value, dict):
        return str(value.get("#text", "")).strip()
    return str(value or "").strip()


def parse_subpages(payload: str, *, context: str) -> list[Page]:
    """Turn a Deki subpages response into ``Page`` records, in document order."""

    try:
        document = json.loads(payload)
    except json.JSONDecodeError as error:
        raise SeedGeneratorError(f"{context}: response was not JSON") from error
    if not isinstance(document, dict):
        raise SeedGeneratorError(f"{context}: unexpected API response shape")

    raw = document.get("page.subpage", [])
    # Deki collapses a single-element list into a bare object.
    if isinstance(raw, dict):
        raw = [raw]
    if not isinstance(raw, list):
        raise SeedGeneratorError(f"{context}: unexpected subpage payload")

    pages: list[Page] = []
    for entry in raw:
        if not isinstance(entry, dict):
            continue
        url = _text_of(entry.get("uri.ui"))
        title = _text_of(entry.get("title"))
        if not url or not title:
            # A malformed row is skipped rather than fatal: one bad page should
            # not cost the other 250.
            continue
        pages.append(
            Page(
                title=title,
                canonical_url=url,
                has_children=str(entry.get("@subpages", "")).lower() == "true",
            )
        )
    return pages


def is_content_chapter(page: Page) -> bool:
    """Whether a top-level page is a real chapter rather than front/back matter."""

    return page.title.strip().lower() not in SKIPPED_TITLES


def is_api_unavailable(error: Exception) -> bool:
    """Whether an API failure means "use the HTML instead" rather than "stop".

    The Deki API is enabled per subdomain. ``chem.libretexts.org`` serves it
    anonymously; ``bio.libretexts.org`` answers 403 with
    ``TokenValidationFailedException``. Both render the same public page HTML,
    so an auth failure is a reason to change source, not to give up.
    """

    message = str(error).lower()
    return any(
        marker in message
        for marker in ("http 401", "http 403", "http 404", "token", "forbidden")
    )


def parse_listing_html(payload: str, page_url: str, *, context: str) -> list[Page]:
    """Extract a page's direct children from its rendered table of contents.

    Selection is by URL, not by CSS class: a book's landing page renders
    ``mt-sortable-listing-link`` anchors, but its chapter pages render plain
    ``class="internal"`` ones, so keying on the class found the chapters and
    then reported every chapter as empty. Any anchor pointing at a direct
    child of this page is a subpage link.

    Titles prefer the ``mt-sortable-listing-title`` span, then the anchor's own
    text, and only then the ``title`` attribute -- which on some books carries
    the whole chapter summary appended to the title.
    """

    prefix = normalize_source_url(page_url) + "/"
    pages: list[Page] = []
    seen: set[str] = set()

    for match in _LISTING_ANCHOR_RE.finditer(payload):
        open_tag, inner = match.group(1), match.group(2)
        href_match = _HREF_RE.search(open_tag)
        if not href_match:
            continue
        url = normalize_source_url(html.unescape(href_match.group(1)))
        if not url.startswith(prefix) or "/" in url[len(prefix) :]:
            continue  # not a direct child
        if url in seen:
            continue

        span = _TITLE_SPAN_RE.search(inner)
        title = _strip_tags(span.group(1)) if span else ""
        if not title:
            title = _strip_tags(inner)
        if not title:
            attr = _TITLE_ATTR_RE.search(open_tag)
            title = html.unescape(attr.group(1)).strip() if attr else ""
        if not title:
            continue
        seen.add(url)
        pages.append(Page(title=title, canonical_url=url, has_children=True))

    # An empty result is normal: a leaf page has no listing. Callers decide
    # whether that is a problem -- an empty *book* is caught by fetch_outline.
    return pages


def _strip_tags(fragment: str) -> str:
    return html.unescape(re.sub(r"<[^>]+>", " ", fragment)).strip()


def fetch_children(page_url: str, *, http_get: HttpGet) -> list[Page]:
    """Direct child pages of a page, via the API where it is open to us."""

    try:
        return parse_subpages(http_get(subpages_api_url(page_url)), context=page_url)
    except SeedGeneratorError as error:
        if not is_api_unavailable(error):
            raise
    return parse_listing_html(http_get(page_url), page_url, context=page_url)


def fetch_outline(
    book_url: str,
    *,
    http_get: HttpGet = _http_get,
    book_title: str | None = None,
) -> BookOutline:
    """Read a book's chapters and their topic pages."""

    book_url = normalize_source_url(book_url)
    chapters = [
        page
        for page in fetch_children(book_url, http_get=http_get)
        if is_content_chapter(page)
    ]
    if not chapters:
        raise SeedGeneratorError(f"{book_url}: no content chapters found")

    outline = BookOutline(
        source_url=book_url,
        title=book_title or _title_from_url(book_url),
    )
    for chapter in chapters:
        topics = [
            topic
            for topic in fetch_children(chapter.canonical_url, http_get=http_get)
            if is_content_chapter(topic)
        ]
        if topics:
            outline.chapters.append((chapter, topics))
    if not outline.chapters:
        raise SeedGeneratorError(f"{book_url}: no chapter contained any pages")
    return outline


def _title_from_url(book_url: str) -> str:
    slug = urllib.parse.unquote(normalize_source_url(book_url).rsplit("/", 1)[-1])
    return slug.replace("_", " ").strip()


def build_seed(
    outline: BookOutline,
    *,
    author: str,
    license_code: str,
    license_version: str | None,
    description: str | None = None,
    descriptor_type: str = "Learning Objective",
) -> dict[str, Any]:
    """Assemble a seed document from an outline. Pure: no network."""

    namespace = namespace_for(outline.source_url)
    seen_urls: set[str] = set()
    chapters: list[dict[str, Any]] = []

    for chapter_order, (chapter, topics) in enumerate(outline.chapters, start=1):
        topic_entries: list[dict[str, Any]] = []
        for topic_order, topic in enumerate(topics, start=1):
            normalized = normalize_source_url(topic.canonical_url)
            if normalized in seen_urls:
                # catalog.py rejects the whole catalog on a duplicate topic URL,
                # so drop the repeat here instead of shipping an unloadable seed.
                continue
            seen_urls.add(normalized)
            topic_entries.append(
                {
                    "order": topic_order,
                    "title": topic.title,
                    # Store the normalized form so a seed does not change shape
                    # just because the API's encoding of a page did.
                    "canonical_url": normalized,
                    "stable_id": stable_id_for(namespace, normalized),
                }
            )
        if not topic_entries:
            continue
        chapter_url = normalize_source_url(chapter.canonical_url)
        chapters.append(
            {
                "order": chapter_order,
                "title": chapter.title,
                "canonical_url": chapter_url,
                "stable_id": stable_id_for(namespace, chapter_url),
                "topics": topic_entries,
            }
        )

    if not chapters:
        raise SeedGeneratorError(f"{outline.source_url}: no publishable topics")

    return {
        "schema_version": SCHEMA_VERSION,
        "framework": {
            "title": outline.title,
            "author": author,
            "descriptor_type": descriptor_type,
            "description": description
            or (
                f"Curated chapter and page-topic alignment for the LibreTexts "
                f"{outline.title} book."
            ),
            "license": license_code,
            "license_version": license_version,
            "source_url": outline.source_url,
        },
        "stable_id_namespace": str(namespace),
        "chapters": chapters,
    }


def topic_ids(seed: dict[str, Any]) -> dict[str, str]:
    """Map normalized topic URL -> stable_id, for comparing two seeds."""

    return {
        normalize_source_url(str(topic["canonical_url"])): str(topic["stable_id"])
        for chapter in seed.get("chapters", [])
        for topic in chapter.get("topics", [])
    }


def conflicting_topic_ids(
    existing: dict[str, Any], candidate: dict[str, Any]
) -> list[str]:
    """URLs present in both seeds whose stable_id would change.

    A changed ID breaks ``alignment_by_topic_id`` for anything already
    published against the old value, so this is the check that makes
    overwriting safe.
    """

    old, new = topic_ids(existing), topic_ids(candidate)
    return sorted(url for url, value in old.items() if url in new and new[url] != value)


def render(seed: dict[str, Any]) -> str:
    return json.dumps(seed, indent=2, ensure_ascii=False) + "\n"


def _count_topics(seed: dict[str, Any]) -> int:
    return sum(len(chapter["topics"]) for chapter in seed["chapters"])


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a curated framework catalog seed for a LibreTexts book.",
    )
    parser.add_argument("book_url", help="URL of the book's landing page")
    parser.add_argument("--author", required=True, help="Book author, as credited")
    parser.add_argument(
        "--license",
        required=True,
        choices=["publicdomain", "ccby", "ccbync", "ccbyncsa", "ccbysa", "arr"],
        help="License code shown on the book",
    )
    parser.add_argument("--license-version", default=None, help='e.g. "4.0"')
    parser.add_argument("--title", default=None, help="Override the book title")
    parser.add_argument("--description", default=None)
    parser.add_argument(
        "--out",
        default="-",
        help="Output path, or - for stdout (default)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing seed even if topic stable_ids would change",
    )
    args = parser.parse_args(argv)

    try:
        outline = fetch_outline(args.book_url, book_title=args.title)
        seed = build_seed(
            outline,
            author=args.author,
            license_code=args.license,
            license_version=args.license_version,
            description=args.description,
        )
    except SeedGeneratorError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if args.out != "-":
        from pathlib import Path

        destination = Path(args.out)
        if destination.exists():
            try:
                existing = json.loads(destination.read_text())
            except (OSError, json.JSONDecodeError):
                existing = None
            if isinstance(existing, dict):
                conflicts = conflicting_topic_ids(existing, seed)
                if conflicts and not args.force:
                    print(
                        f"error: {destination} already exists and {len(conflicts)} "
                        "topic stable_id(s) would change. Questions already "
                        "published against those topics would stop resolving. "
                        "Re-run with --force only if that is intended.",
                        file=sys.stderr,
                    )
                    for url in conflicts[:5]:
                        print(f"  {url}", file=sys.stderr)
                    return 2
        destination.write_text(render(seed))
        print(
            f"wrote {destination}: {len(seed['chapters'])} chapters, "
            f"{_count_topics(seed)} publishable topics",
            file=sys.stderr,
        )
        print(
            "next: copy this file to BOTH app/catalogs/ (Assessment AI) and "
            "resources/frameworks/ (ADAPT) -- verify_framework_catalogs.py "
            "requires them byte-identical -- then rebuild both images.",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(render(seed))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
